[package]
name = "png_decode"
version = "0.1.0"
authors = ["David Kleingeld <dskleingeld@gmail.com>"]

[dependencies]
libc = "*"
image = "0.20.0"

[lib]
crate-type = ["cdylib"]
#crate-type= ["staticlib"] #gives link error in C
